/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reddev112.piet;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Tyler
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pietPanel = new com.reddev112.piet.PietPanel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputPane = new javax.swing.JEditorPane();
        nextBtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        runBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jFileOpenMenu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        outlineCurrMenu = new javax.swing.JCheckBoxMenuItem();
        showValueMenu = new javax.swing.JCheckBoxMenuItem();
        setCodelWidthMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        displayPanel.setLayout(new javax.swing.BoxLayout(displayPanel, javax.swing.BoxLayout.X_AXIS));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(600, 700));

        javax.swing.GroupLayout pietPanelLayout = new javax.swing.GroupLayout(pietPanel);
        pietPanel.setLayout(pietPanelLayout);
        pietPanelLayout.setHorizontalGroup(
            pietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        pietPanelLayout.setVerticalGroup(
            pietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pietPanel);

        displayPanel.add(jScrollPane1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        displayPanel.add(jSeparator1);

        buttonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        outputPane.setAutoscrolls(false);
        jScrollPane2.setViewportView(outputPane);

        buttonPanel.add(jScrollPane2);

        nextBtn.setText("Next Codel");
        nextBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(nextBtn);
        buttonPanel.add(filler1);

        runBtn.setText("Run Program");
        runBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(runBtn);

        resetBtn.setText("Reset Program");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(resetBtn);
        buttonPanel.add(filler2);

        displayPanel.add(buttonPanel);

        getContentPane().add(displayPanel);

        fileMenu.setText("File");

        jFileOpenMenu.setText("Open...");
        jFileOpenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jFileOpenMenuMouseReleased(evt);
            }
        });
        fileMenu.add(jFileOpenMenu);

        jMenuBar.add(fileMenu);

        editMenu.setText("View");

        outlineCurrMenu.setSelected(true);
        outlineCurrMenu.setText("Outline Current Codel");
        outlineCurrMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outlineCurrMenuActionPerformed(evt);
            }
        });
        editMenu.add(outlineCurrMenu);

        showValueMenu.setText("Show Codel Block Values");
        showValueMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showValueMenuActionPerformed(evt);
            }
        });
        editMenu.add(showValueMenu);

        setCodelWidthMenu.setText("Codel Width");
        setCodelWidthMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCodelWidthMenuActionPerformed(evt);
            }
        });
        editMenu.add(setCodelWidthMenu);

        jMenuBar.add(editMenu);

        helpMenu.setText("Help");
        jMenuBar.add(helpMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileOpenMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFileOpenMenuMouseReleased
        if (evt.getSource() == jFileOpenMenu) {
            int returnValue = fileChooser.showOpenDialog(this);
            
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                BufferedImage image = null;
                try {
                    image = ImageIO.read(file);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                if (image != null) {
                    program = new PietProgram(image);
                    
                    program.setCallback(new PietProgram.InIntCallback() {
                        @Override
                        public int onInInt() {
                            return 0;
                        }
                    });
                    
                    program.setCallback(new PietProgram.InStrCallback() {
                        @Override
                        public String onInStr() {
                            return "";
                        }
                    });
                    
                    program.setCallback(new PietProgram.OutIntCallback() {
                        @Override
                        public void onOutInt(int value) {
                            
                        }
                    });
                    
                    pietPanel.loadPietProgram(program);
                }
            } else {
                System.out.println("File Chooser not approved.");
            }
        }
    }//GEN-LAST:event_jFileOpenMenuMouseReleased

    private void display(int output, boolean toChar) {
        
    }
    
    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
//        System.out.println("Button pressed.");
        if (evt.getSource() == nextBtn) {
            if (program != null) {
                // For some reason, it requires two clicks to progress
                // with just one step() statement, so I just added a second.
                program.step();
                program.step();
                pietPanel.repaint();
                
                if (program.isComplete()) {
                    runBtn.setEnabled(false);
                    nextBtn.setEnabled(false);
                }
            }
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void runBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBtnActionPerformed
        if (evt.getSource() == runBtn) {
            if (program != null) {
                program.run();
                pietPanel.repaint();
                runBtn.setEnabled(false);
                runBtn.setEnabled(false);
            }
        }
    }//GEN-LAST:event_runBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        if (evt.getSource() == resetBtn) {
            if (program != null) {
                program.reset();
                pietPanel.repaint();
                runBtn.setEnabled(true);
                nextBtn.setEnabled(true);
            }
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    private void setCodelWidthMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCodelWidthMenuActionPerformed
        if (program != null) {
            int oldWidth = pietPanel.getCodelWidth();
            String input = (String) JOptionPane.showInputDialog(pietPanel, "Enter the codel width (in pixels):", "Set Codel Width", JOptionPane.PLAIN_MESSAGE, null, null, oldWidth);
            int width = Integer.valueOf(input);
            pietPanel.setCodelWidth(width);
            pietPanel.repaint();
        }
    }//GEN-LAST:event_setCodelWidthMenuActionPerformed

    private void outlineCurrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outlineCurrMenuActionPerformed
        if (evt.getSource() == outlineCurrMenu) {
            boolean selected = outlineCurrMenu.isSelected();
            pietPanel.outlineCurrent(selected);
            pietPanel.repaint();
        }
    }//GEN-LAST:event_outlineCurrMenuActionPerformed

    private void showValueMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showValueMenuActionPerformed
        if (evt.getSource() == showValueMenu) {
            boolean selected = showValueMenu.isSelected();
            pietPanel.showValue(selected);
            pietPanel.repaint();
        }
    }//GEN-LAST:event_showValueMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    private final JFileChooser fileChooser = new JFileChooser("C:\\Users\\Tyler D Caudell\\Downloads\\npiet-1.3a-win32\\examples");
    private PietProgram program;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jFileOpenMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JCheckBoxMenuItem outlineCurrMenu;
    private javax.swing.JEditorPane outputPane;
    private com.reddev112.piet.PietPanel pietPanel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton runBtn;
    private javax.swing.JMenuItem setCodelWidthMenu;
    private javax.swing.JCheckBoxMenuItem showValueMenu;
    // End of variables declaration//GEN-END:variables
}
